# Configuración para Read the Docs
version: 2

# Lenguaje de la documentación
sphinx:
  configuration: docs/conf.py  # Ubicación del archivo de configuración de Sphinx

# Configuración del entorno de construcción
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Dependencias necesarias para construir la documentación
python:
  install:
    - requirements: docs/requirements.txt  # Lista de dependencias para la documentación
    - method: pip
      path: .

# Configuración de formatos de salida
formats:
  - "htmlzip"
  - "pdf"
  - "epub"

# Configuración avanzada
builds:
  commands:
    - echo "🚀 Construyendo la documentación para Open Science & AI"
