# Configuración para Read the Docs
version: 2

# Configuración del entorno de Sphinx
sphinx:
  configuration: docs/conf.py  # Ubicación del archivo de configuración de Sphinx

# Configuración del entorno de construcción
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

# Instalación de dependencias
python:
  install:
    - requirements: docs/requirements.txt  # Instalación de dependencias de Sphinx desde requirements.txt

# Configuración de formatos de salida de documentación
formats:
  - "htmlzip"
  - "pdf"
  - "epub"

